sqlite3 ClassDemo.db
CREATE TABLE 'ClassDemo' ('champ' text, 'node' integer);
INSERT INTO ClassDemo (champ, node) VALUES('Agent Venom', 34);
INSERT INTO ClassDemo (champ, node) VALUES('Wasp', 38);
INSERT INTO ClassDemo (champ, node) VALUES('Medusa', 49);
INSERT INTO ClassDemo (champ, node) VALUES('Thing', 50);
INSERT INTO ClassDemo (champ, node) VALUES('Vision Aarkus', 28);
INSERT INTO ClassDemo (champ, node) VALUES('Agent Venom', 51);
INSERT INTO ClassDemo (champ, node) VALUES('Mephisto', 15);
INSERT INTO ClassDemo (champ, node) VALUES('Black Widow CV', 36);
INSERT INTO ClassDemo (champ, node) VALUES('Man-Thing', 40);
INSERT INTO ClassDemo (champ, node) VALUES('Magneto Classic', 43);
INSERT INTO ClassDemo (champ, node) VALUES('Ebony Maw', 3);
INSERT INTO ClassDemo (champ, node) VALUES('Longshot', 25);
INSERT INTO ClassDemo (champ, node) VALUES('Mordo', 1);
INSERT INTO ClassDemo (champ, node) VALUES('Nightcrawler', 29);
INSERT INTO ClassDemo (champ, node) VALUES('Mole Man', 22);
INSERT INTO ClassDemo (champ, node) VALUES('Korg', 23);
INSERT INTO ClassDemo (champ, node) VALUES('Doctor Doom', 46);
INSERT INTO ClassDemo (champ, node) VALUES('Thing', 55);
INSERT INTO ClassDemo (champ, node) VALUES('Sorcerer Supreme', 12);
INSERT INTO ClassDemo (champ, node) VALUES('Thor Ragnarok', 39);
INSERT INTO ClassDemo (champ, node) VALUES('Agent Venom', 15);
INSERT INTO ClassDemo (champ, node) VALUES('Morningstar', 45);
INSERT INTO ClassDemo (champ, node) VALUES('Havok', 31);
INSERT INTO ClassDemo (champ, node) VALUES('Black Widow Origin', 19);
INSERT INTO ClassDemo (champ, node) VALUES('Morningstar', 27);
INSERT INTO ClassDemo (champ, node) VALUES('Venom', 9);
INSERT INTO ClassDemo (champ, node) VALUES('Red Goblin', 13);
INSERT INTO ClassDemo (champ, node) VALUES('Agent Venom', 17);
INSERT INTO ClassDemo (champ, node) VALUES('Spider-Man Stealth', 41);
INSERT INTO ClassDemo (champ, node) VALUES('Magneto X', 2);
INSERT INTO ClassDemo (champ, node) VALUES('Yondu', 6);
INSERT INTO ClassDemo (champ, node) VALUES('Emma Frost', 26);
INSERT INTO ClassDemo (champ, node) VALUES('Red Goblin', 21);
INSERT INTO ClassDemo (champ, node) VALUES('King Groot', 44);
INSERT INTO ClassDemo (champ, node) VALUES('Magik', 24);
INSERT INTO ClassDemo (champ, node) VALUES('Red Goblin', 35);
INSERT INTO ClassDemo (champ, node) VALUES('Iceman', 5D);
INSERT INTO ClassDemo (champ, node) VALUES('Killmonger', 90);
INSERT INTO ClassDemo (champ, node) VALUES('Terrax', 49);
INSERT INTO ClassDemo (champ, node) VALUES('Mysterio', 18);
INSERT INTO ClassDemo (champ, node) VALUES('Nick Fury', 44);
INSERT INTO ClassDemo (champ, node) VALUES('Dragon Man', 52);
INSERT INTO ClassDemo (champ, node) VALUES('Professor X', 37);
INSERT INTO ClassDemo (champ, node) VALUES('Iron Man', 20);
INSERT INTO ClassDemo (champ, node) VALUES('Apocalypse', 47);
INSERT INTO ClassDemo (champ, node) VALUES('Punisher 2099', 7);
INSERT INTO ClassDemo (champ, node) VALUES('Domino', 40);
INSERT INTO ClassDemo (champ, node) VALUES('Aegon', 8);
INSERT INTO ClassDemo (champ, node) VALUES('Sunspot', 16);
INSERT INTO ClassDemo (champ, node) VALUES('Vision Aarkus', 54);
INSERT INTO ClassDemo (champ, node) VALUES('Agent Venom', 15);
INSERT INTO ClassDemo (champ, node) VALUES('Morningstar', 45);
INSERT INTO ClassDemo (champ, node) VALUES('Havok', 31);
INSERT INTO ClassDemo (champ, node) VALUES('Black Widow Origin', 19);
INSERT INTO ClassDemo (champ, node) VALUES('Symbiote Supreme', 27);
INSERT INTO ClassDemo (champ, node) VALUES('Venom', 9);
INSERT INTO ClassDemo (champ, node) VALUES('Red Goblin', 13);
INSERT INTO ClassDemo (champ, node) VALUES('Killmonger', 17);
INSERT INTO ClassDemo (champ, node) VALUES('Spider-Man Stealth', 41);
INSERT INTO ClassDemo (champ, node) VALUES('Magneto X', 18);
